containers:
  mongodb:
    stack:
      - nosql
      - mongo
      - mongodb
    versioning:
      mongodb: mongo --version | head -n 1 | sed 's/^MongoDB shell version v//'
    image:
      name: bitnami/mongodb
      use_alpine: false
    volumes:
      named:
        data: /bitnami/mongodb
    env:
      prefixed:
        MONGODB_ROOT_PASSWORD: root_password
        MONGODB_USERNAME: user
        MONGODB_PASSWORD: password
        MONGODB_DATABASE: database
      exported:
        - user
        - password
        - database
        - root_password
        - host
    ports:
      db: 27017
