elixir_phoenix:
  required:
    - database
  build:
    context: build/${ENV}/elixir/phoenix
    args:
      TAG: "%(tag:1.9-alpine)"
      USERID: ${USERID}
      GROUPID: ${GROUPID}
  volumes:
    mapped:
      - "%(project.path):/app"
  env:
    imported:
      DB_USER: database.user
      DB_PASSWORD: database.password
      DB_PORT: database.port
      DB_HOST: database
  ports:
    4000:
      env: PORT
