elixir_phoenix:
  build:
    context: build/${ENV}/elixir/phoenix
    args:
      TAG: "%(tag:1.9-alpine)"
      USERID: ${USERID}
      GROUPID: ${GROUPID}
  volumes:
    mapped:
      - "%(project.path):/app"
  env:
    imported:
      - database.user
      - database.password
      - database.database
      - database.port
  ports:
    4000:
      env: PORT
