version: '3'

services:
  %(name):
    build:
      context: build/${ENV}/elixir/phoenix
      args:
        TAG: %(tag:1.9-alpine)
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    volumes:
      - %(project.path):/app
