containers:
  postgres:
    stack:
      - sql
      - postgres
    image:
      name: postgres
      tag: "%(service.version:12)-alpine"
    volumes:
      named:
        data: /var/lib/postgresql/data
    env:
      prefixed:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: database
      exported:
        - user
        - password
        - database
        - port
    ports:
      5432:
        env: port
