containers:
  postgres:
    stack:
      - sql
      - postgres
    versioning:
      postgres: postgres -V | sed 's/^postgres (PostgreSQL) //'
    image:
      name: postgres
    volumes:
      named:
        data: /var/lib/postgresql/data
    env:
      prefixed:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: database
      exported:
        - user
        - password
        - database
        - host
    ports:
      db: 5432
