containers:
  postgres:
    stack:
      - sql
      - postgres
    image:
      name: postgres
    volumes:
      named:
        data: /var/lib/postgresql/data
    env:
      prefixed:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: database
    ports:
      db: 5432
