containers:
  nest:
    stack:
      - node
      - nest
    build:
      name: node
      use_alpine: true
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    volumes:
      mapped:
        - %= project.path =%:/app
    env:
      mapped:
        - base_url
      imported:
        DB_USER: database.user
        DB_PASSWORD: database.password
        DB_PORT: database.port
        DB_HOST: database.host
    ports:
      http: 3000
