required:
  - database
containers:
  elixir_phoenix:
    stack:
      - http
      - elixir
      - phoenix
    build:
      context: build/${ENV}/elixir/phoenix
      args:
        TAG: %= service.version.elixir if service.version.elixir else defaults.elixir.version =%-alpine
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    volumes:
      mapped:
        - %= project.path =%:/app
    env:
      imported:
        DB_USER: database.user
        DB_PASSWORD: database.password
        DB_PORT: database.port
        DB_HOST: database.host
      exported:
        - port
    ports:
      http_port:
        default: 4000
        env: port
