required:
  - targets
references:
  - service.targets:web.build.params.targets
containers:
  web:
    stack:
      - http
      - nginx
    build:
      context: build/%= env.env =%/nginx/proxy
      params:
        targets: references
      args:
        TAG: %= service|version('nginx', defaults) =%-alpine
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    env:
      exported:
        - http_port
        - https_port
    ports:
      http_port:
        default: 80
        env: http_port
      https_port:
        default: 443
        env: https_port