required:
  - targets
params:
  targets: %= service.get_required('targets') =%
containers:
  web:
    stack:
      - http
      - nginx
    build:
      name: nginx
      use_alpine: true
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    env:
      exported:
        - http_port
        - https_port
    ports:
      http: 80
      https: 443
