containers:
  angular:
    stack:
      - node
      - angular
    build:
      context: build/%= env.env =%/node/angular
      args:
        TAG: %= service|version('node', defaults) =%-alpine
        ANGULAR_VERSION: %= service|version('angular', defaults) =%
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    volumes:
      mapped:
        - %= project.path =%:/app
    env:
      mapped:
        - base_url
      exported:
        - http_port
    ports:
      http_port:
        default: 4200
        env: http_port
