#!/usr/bin/env bash

# dependencies
source ${PROJECT_PATH}/devdock/env/utils/python.rc
if [ "$1" == "deps" ]; then
    bash ${PROJECT_PATH}/devdock/env/dev-deps
    exit 0
fi
# try run command
if [ -z $CLI_COMMAND ]; then export CLI_COMMAND=$(basename "$0"); fi
py_cmd=$(get_python_runtime)
if [ $? -eq 0 ]; then
    $py_cmd ${PROJECT_PATH}/devdock/tools/cli.py $*
else
    echo -e "error: $py_cmd"
fi
